//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public int ID { get; set; }
        public int FamilyID { get; set; }
        public string Name { get; set; }
        public string Grade { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    
        public virtual Family Family { get; set; }
    }
}
